<?php
/**
 * Application Form 
 *
 */
/*function application_details_form($form,&$form_state){
    $form['first_name'] = array(
        '#type' => 'textfield',
        '#title' => t('YOUR NAME'),
        '#size' => 10,
        '#required' => TRUE,
    );
    $form['middle_name'] = array(
        '#type' => 'textfield',
        '#title' => t(''),
        '#size' => 10,
    );
    $form['last_name'] = array(
        '#type' => 'textfield',
        '#title' => t(''),
        '#size' => 10
    );
    $form['last_name12'] = array(
        '#type' => 'textfield',
        '#title' => t('FFF'),
        '#size' => 10
    );
    $active = array(0 => t('Closed'), 1 => t('Active'));
   $form['active'] = array(
    '#type' => 'radios',
    '#title' => t('Poll status'),
    
    '#options' => $active,
    '#description' => t('When a poll is closed, visitors can no longer vote for it.'),
  );

    return $form;
}*/
?>